### ISSUE TITLE
Stuck while generating backup

### ISSUE THREAD

**Issue by kuroni** [Grace5921/TwrpBuilder#15]
```
Brand : Nokia
Model : Nokia 6.1
Board : SDM630
Running in non-root mode
```

Whenever I try to generate a backup, the app crashes and reports `Twrp Builder has stopped`.

**Comment by surendrajat** [comment]
Please provide `logcat`...

**Comment by kuroni** [comment]
Sorry for the late reply :(

I used this command: `adb logcat AndroidRuntime:* *:S -v long > a.txt`

<details>
<summary> Output:
</summary>

```
--------- beginning of system
--------- beginning of crash
[ 07-04 15:42:50.117 12604:12604 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 12604
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


--------- beginning of main
[ 07-04 18:45:54.081 23886:23886 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:45:54.085 23886:23886 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 23886
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 18:45:57.365 24872:24872 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:45:57.370 24872:24872 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 24872
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.TwrpBuilder/com.github.TwrpBuilder.MainActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at com.google.firebase.database.FirebaseDatabase.getReference(Unknown Source:9)
	at com.github.TwrpBuilder.Fragment.FragmentStatusCommon.onCreateView(FragmentStatusCommon.java:63)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7056)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more


[ 07-04 18:47:21.327 25784:25784 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:47:21.328 25784:25784 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 25784
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 18:47:23.038 25938:25938 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:47:23.041 25938:25938 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 25938
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.TwrpBuilder/com.github.TwrpBuilder.MainActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at com.google.firebase.database.FirebaseDatabase.getReference(Unknown Source:9)
	at com.github.TwrpBuilder.Fragment.FragmentStatusCommon.onCreateView(FragmentStatusCommon.java:63)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7056)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more


[ 07-04 18:48:19.037 26216:26216 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:48:19.037 26216:26216 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 26216
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 18:48:22.491 26290:26290 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:48:22.495 26290:26290 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 26290
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.TwrpBuilder/com.github.TwrpBuilder.MainActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at com.google.firebase.database.FirebaseDatabase.getReference(Unknown Source:9)
	at com.github.TwrpBuilder.Fragment.FragmentStatusCommon.onCreateView(FragmentStatusCommon.java:63)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7056)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more


[ 07-04 18:50:00.608 26443:26443 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:50:00.609 26443:26443 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 26443
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 18:50:03.111 26528:26528 D/AndroidRuntime ]
Shutting down VM


[ 07-04 18:50:03.119 26528:26528 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 26528
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.TwrpBuilder/com.github.TwrpBuilder.MainActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at com.google.firebase.database.FirebaseDatabase.getReference(Unknown Source:9)
	at com.github.TwrpBuilder.Fragment.FragmentStatusCommon.onCreateView(FragmentStatusCommon.java:63)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7056)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more


[ 07-04 19:10:03.885 27814:27814 D/AndroidRuntime ]
Shutting down VM


[ 07-04 19:10:03.886 27814:27814 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 27814
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 19:10:05.510 27919:27919 D/AndroidRuntime ]
Shutting down VM


[ 07-04 19:10:05.514 27919:27919 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 27919
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.TwrpBuilder/com.github.TwrpBuilder.MainActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at com.google.firebase.database.FirebaseDatabase.getReference(Unknown Source:9)
	at com.github.TwrpBuilder.Fragment.FragmentStatusCommon.onCreateView(FragmentStatusCommon.java:63)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7056)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more


[ 07-04 19:10:31.520 28015:28015 D/AndroidRuntime ]
Shutting down VM


[ 07-04 19:10:31.520 28015:28015 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 28015
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 19:12:01.017 28248:28248 D/AndroidRuntime ]
Shutting down VM


[ 07-04 19:12:01.017 28248:28248 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 28248
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 19:12:15.003 28336:28336 D/AndroidRuntime ]
Shutting down VM


[ 07-04 19:12:15.009 28336:28336 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 28336
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.TwrpBuilder/com.github.TwrpBuilder.MainActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in FirebaseDatabase.getReference()
	at com.google.firebase.database.FirebaseDatabase.getReference(Unknown Source:9)
	at com.github.TwrpBuilder.Fragment.FragmentStatusCommon.onCreateView(FragmentStatusCommon.java:63)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7056)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more


[ 07-04 19:12:25.192 28412:28412 D/AndroidRuntime ]
Shutting down VM


[ 07-04 19:12:25.192 28412:28412 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 28412
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


[ 07-04 19:13:31.450 28562:28562 D/AndroidRuntime ]
Shutting down VM


[ 07-04 19:13:31.450 28562:28562 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.github.TwrpBuilder, PID: 28562
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at com.github.TwrpBuilder.app.CustomBackupActivity$3.onClick(CustomBackupActivity.java:85)
	at android.view.View.performClick(View.java:6305)
	at android.view.View$PerformClick.run(View.java:24840)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
</details>

**Comment by surendrajat** [comment]
I think I got it. Will look into it as soon I get time.
BTW you're using `TwrpBuilder-v5.1` ?

**Comment by kuroni** [comment]
Yes I am.
